scp -P portnumber install.sh username@c220ipaddress:~/
scp -P portnumber install.sh username@c220ipaddress:~/
scp -P portnumber install.sh username@c220ipaddress:~/
scp -P portnumber install.sh username@c220ipaddress:~/
scp -P portnumber install.sh username@c220ipaddress:~/
scp -P portnumber install.sh username@c220ipaddress:~/
scp -P portnumber install.sh username@c220ipaddress:~/
scp -P portnumber install.sh username@c220ipaddress:~/
scp -P portnumber install.sh username@c220ipaddress:~/
scp -P portnumber install.sh username@c220ipaddress:~/
